version: '3'
services:
  redis:
      image: redis:3
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./docker-data/redis-cluster.tmpl:/usr/local/etc/redis/redis.conf
        - /data/redis-cluster/redis:/data
      command: redis-server /usr/local/etc/redis/redis.conf
      network_mode: host
      restart: always

  redis-cluster:
    tty: true
    build:
      context: .
      args:
        redis_version: '3.2.9'
    hostname: server
    network_mode: host
